### ISSUE TITLE
Einheitliche Bezeichnung von Success Factor

### ISSUE THREAD

**Issue by axelplore** [axelplore/ERP-Systeme-Seminararbeit#12]
Unterschiedliche Bezeichnung: SuccessFactors <> Success Factors <> Success-Factors
Nach deutscher Rechtschreibung wäre Success Factors oder Success-Factors richtig.

In 4.3.2 einmal SAP-Succes-Factors --> korrigieren

4.3 Aussichten und Vergleich mit dem neuen SuccessFactors, richtig?

**Comment by ZachariasFrings** [comment]
Wurde korrigiert
